from __future__ import annotations

RULE_CATALOG = [
    {
        "rule_id": "DISCLOSURE_DELAY_001",
        "name": "重大事项披露时效",
        "description": "发生重大事件后，应按规则及时履行信息披露义务。",
        "scenario_tags": ["重大事项", "停牌", "并购", "诉讼仲裁", "对外担保", "重大合同"],
        "inputs": ["event_date", "disclosure_date", "materiality", "exchange"],
        "logic": {
            "type": "date_diff_lte",
            "left": "event_date",
            "right": "disclosure_date",
            "days": 2,
            "when": {"materiality": ["high", "重大", "material"]},
        },
        "severity_on_fail": "high",
        "legal_basis_keywords": ["信息披露", "上市规则", "重大事项", "临时报告"],
        "explanation": "示例阈值为内部风控预警阈值，不直接替代法律意见。",
    },
    {
        "rule_id": "RELATED_PARTY_001",
        "name": "关联交易审批与披露",
        "description": "关联交易达到内部阈值时，需检查审议程序、关联董事回避、信息披露。",
        "scenario_tags": ["关联交易", "日常关联交易", "关联担保", "资金占用"],
        "inputs": ["related_party_transaction", "transaction_amount", "board_approved", "independent_director_opinion", "disclosed"],
        "logic": {
            "type": "all_required_if",
            "when": {"related_party_transaction": True, "transaction_amount_gte": 10000000},
            "required": ["board_approved", "disclosed"],
            "truthy": ["board_approved", "disclosed"],
        },
        "severity_on_fail": "high",
        "legal_basis_keywords": ["关联交易", "公司治理", "董事会", "信息披露"],
        "explanation": "金额阈值为默认示例，实际阈值应结合板块、最近一期财务指标与现行规则调整。",
    },
    {
        "rule_id": "REDUCTION_001",
        "name": "董监高或股东减持合规",
        "description": "检查减持计划披露、窗口期、敏感期限制与承诺约束。",
        "scenario_tags": ["减持", "董监高", "股东减持", "股份变动"],
        "inputs": ["share_reduction", "plan_disclosed", "sensitive_window", "commitment_restriction"],
        "logic": {
            "type": "must_be_false_and_true",
            "when": {"share_reduction": True},
            "must_be_true": ["plan_disclosed"],
            "must_be_false": ["sensitive_window", "commitment_restriction"],
        },
        "severity_on_fail": "high",
        "legal_basis_keywords": ["减持", "窗口期", "股份变动", "承诺"],
        "explanation": "用于识别明显风险，不代替券商/律所专项核查。",
    },
    {
        "rule_id": "PLEDGE_001",
        "name": "高比例质押预警",
        "description": "股东质押比例过高时触发风控复核。",
        "scenario_tags": ["股权质押", "控股股东", "平仓风险"],
        "inputs": ["pledge_ratio"],
        "logic": {"type": "number_lte", "field": "pledge_ratio", "threshold": 50},
        "severity_on_fail": "medium",
        "legal_basis_keywords": ["股权质押", "风险提示", "控股股东"],
        "explanation": "50% 为默认预警线，可根据内部制度调整。",
    },
    {
        "rule_id": "ENFORCEMENT_001",
        "name": "处罚/立案/监管函舆情命中",
        "description": "若公告或公开信息命中处罚、立案、纪律处分等关键词，则触发风险标记。",
        "scenario_tags": ["行政处罚", "立案", "纪律处分", "监管函", "问询函"],
        "inputs": ["public_text_hits"],
        "logic": {"type": "keyword_absence", "field": "public_text_hits", "keywords": ["立案", "处罚", "纪律处分", "监管函", "问询函", "失信", "被执行人"]},
        "severity_on_fail": "high",
        "legal_basis_keywords": ["行政处罚", "监管措施", "纪律处分"],
        "explanation": "命中后建议人工复核事实背景、时间与主体一致性。",
    },
]
